<?php
if (!defined('ABSPATH')) { exit; }

abstract class EU_Withdrawal_Button_I18n {
    const VERSION = '0.5.0';
    const CPT = 'ewb_withdrawal';
    const OPTION_KEY = 'ewb_settings';
    const NONCE_ACTION = 'ewb_submit_withdrawal';
    const ADMIN_NONCE = 'ewb_admin_action';

    protected $active_lang = null;

    protected function translations(): array {
        return [
            'en'=>[
                'language_name'=>'English','button_label'=>'Withdrawal / Cancel Contract','form_title'=>'Withdrawal / Cancel Contract','form_intro'=>'Use this form to submit an online withdrawal / cancellation request for your order.','lookup_intro'=>'Enter your order number and billing email to retrieve eligible items.','full_name'=>'Full name','email'=>'Email','order_number'=>'Order number','lookup'=>'Find order','products_to_withdraw'=>'Products to withdraw','quantity'=>'Quantity','comments'=>'Comments / additional information','declaration'=>'I hereby declare that I withdraw from the purchase contract for the selected product(s) / order.','review_title'=>'Review and confirm your withdrawal request','back'=>'Back','submit'=>'Confirm withdrawal request','required_fields'=>'Please complete all required fields.','security_failed'=>'Security check failed. Please try again.','order_not_verified'=>'The order could not be verified. Please check your order details.','not_eligible'=>'This order is not currently eligible for online withdrawal. Please contact us if you believe this is incorrect.','no_eligible_items'=>'No eligible items were found for this order.','success_title'=>'Your withdrawal request has been submitted successfully.','success_text'=>'A confirmation email has been sent to your email address.','email_subject'=>'Withdrawal request received','received_body'=>'We have received your withdrawal / cancellation request.','request_id'=>'Request ID','proof_hash'=>'Proof hash','reference_code'=>'Reference code','name'=>'Name','order'=>'Order','submitted_at'=>'Submitted at','products'=>'Product(s)','declaration_label'=>'Declaration','next_steps'=>'You will receive further information regarding the return process and refund, in accordance with the shop policy and applicable law.','admin_new_subject'=>'New withdrawal request - Order','admin_new_request'=>'A new withdrawal request has been submitted.','view_admin'=>'View request in admin','manual_products'=>'Product(s)','manual_products_placeholder'=>'Please enter the product(s) you wish to withdraw from.','status_submitted'=>'Submitted','status_in_review'=>'In Review','status_approved'=>'Approved','status_rejected'=>'Rejected','status_completed'=>'Completed','status_refunded'=>'Refunded'],
            'el'=>[
                'language_name'=>'Greek','button_label'=>'Υπαναχώρηση / Ακύρωση Σύμβασης','form_title'=>'Υπαναχώρηση / Ακύρωση Σύμβασης','form_intro'=>'Χρησιμοποιήστε αυτή τη φόρμα για να υποβάλετε ηλεκτρονικά αίτημα υπαναχώρησης / ακύρωσης για την παραγγελία σας.','lookup_intro'=>'Συμπληρώστε αριθμό παραγγελίας και email χρέωσης για να εμφανιστούν τα επιλέξιμα προϊόντα.','full_name'=>'Ονοματεπώνυμο','email'=>'Email','order_number'=>'Αριθμός παραγγελίας','lookup'=>'Εύρεση παραγγελίας','products_to_withdraw'=>'Προϊόντα για υπαναχώρηση','quantity'=>'Ποσότητα','comments'=>'Σχόλια / πρόσθετες πληροφορίες','declaration'=>'Δηλώνω ότι υπαναχωρώ από τη σύμβαση αγοράς για τα επιλεγμένα προϊόντα / την παραγγελία.','review_title'=>'Έλεγχος και επιβεβαίωση αιτήματος υπαναχώρησης','back'=>'Πίσω','submit'=>'Επιβεβαίωση αιτήματος υπαναχώρησης','required_fields'=>'Παρακαλώ συμπληρώστε όλα τα υποχρεωτικά πεδία.','security_failed'=>'Ο έλεγχος ασφαλείας απέτυχε. Παρακαλώ δοκιμάστε ξανά.','order_not_verified'=>'Η παραγγελία δεν μπόρεσε να επιβεβαιωθεί. Παρακαλώ ελέγξτε τα στοιχεία της παραγγελίας.','not_eligible'=>'Η παραγγελία δεν είναι αυτή τη στιγμή επιλέξιμη για online υπαναχώρηση. Επικοινωνήστε μαζί μας αν θεωρείτε ότι αυτό δεν είναι σωστό.','no_eligible_items'=>'Δεν βρέθηκαν επιλέξιμα προϊόντα για αυτή την παραγγελία.','success_title'=>'Το αίτημα υπαναχώρησης υποβλήθηκε επιτυχώς.','success_text'=>'Έχει σταλεί email επιβεβαίωσης στη διεύθυνση email σας.','email_subject'=>'Παραλάβαμε το αίτημα υπαναχώρησης','received_body'=>'Παραλάβαμε το αίτημα υπαναχώρησης / ακύρωσης.','request_id'=>'Αριθμός αιτήματος','proof_hash'=>'Αποδεικτικό hash','reference_code'=>'Κωδικός αναγνώρισης','name'=>'Ονοματεπώνυμο','order'=>'Παραγγελία','submitted_at'=>'Ημερομηνία υποβολής','products'=>'Προϊόντα','declaration_label'=>'Δήλωση','next_steps'=>'Θα λάβετε νεότερη ενημέρωση σχετικά με τη διαδικασία επιστροφής και επιστροφής χρημάτων, σύμφωνα με την πολιτική του καταστήματος και την ισχύουσα νομοθεσία.','admin_new_subject'=>'Νέο αίτημα υπαναχώρησης - Παραγγελία','admin_new_request'=>'Υποβλήθηκε νέο αίτημα υπαναχώρησης.','view_admin'=>'Προβολή αιτήματος στο admin','manual_products'=>'Προϊόν/προϊόντα','manual_products_placeholder'=>'Συμπληρώστε το προϊόν ή τα προϊόντα για τα οποία επιθυμείτε να υπαναχωρήσετε.','status_submitted'=>'Υποβλήθηκε','status_in_review'=>'Σε έλεγχο','status_approved'=>'Εγκρίθηκε','status_rejected'=>'Απορρίφθηκε','status_completed'=>'Ολοκληρώθηκε','status_refunded'=>'Επιστράφηκε'],
            'es'=>[
                'language_name'=>'Spanish','button_label'=>'Desistimiento / Cancelar contrato','form_title'=>'Desistimiento / Cancelar contrato','form_intro'=>'Utilice este formulario para enviar una solicitud online de desistimiento / cancelación de su pedido.','lookup_intro'=>'Introduzca el número de pedido y el email de facturación para recuperar los artículos elegibles.','full_name'=>'Nombre completo','email'=>'Correo electrónico','order_number'=>'Número de pedido','lookup'=>'Buscar pedido','products_to_withdraw'=>'Productos objeto de desistimiento','quantity'=>'Cantidad','comments'=>'Comentarios / información adicional','declaration'=>'Declaro que desisto del contrato de compra de los productos seleccionados / del pedido.','review_title'=>'Revisar y confirmar la solicitud de desistimiento','back'=>'Volver','submit'=>'Confirmar solicitud de desistimiento','required_fields'=>'Complete todos los campos obligatorios.','security_failed'=>'La comprobación de seguridad ha fallado. Inténtelo de nuevo.','order_not_verified'=>'No se ha podido verificar el pedido. Compruebe los datos del pedido.','not_eligible'=>'Este pedido no es actualmente elegible para desistimiento online. Contáctenos si cree que esto es incorrecto.','no_eligible_items'=>'No se encontraron artículos elegibles para este pedido.','success_title'=>'Su solicitud de desistimiento se ha enviado correctamente.','success_text'=>'Se ha enviado un email de confirmación a su dirección de correo electrónico.','email_subject'=>'Solicitud de desistimiento recibida','received_body'=>'Hemos recibido su solicitud de desistimiento / cancelación.','request_id'=>'ID de solicitud','proof_hash'=>'Hash de prueba','reference_code'=>'Código de referencia','name'=>'Nombre','order'=>'Pedido','submitted_at'=>'Fecha de envío','products'=>'Producto(s)','declaration_label'=>'Declaración','next_steps'=>'Recibirá más información sobre el proceso de devolución y reembolso, de acuerdo con la política de la tienda y la legislación aplicable.','admin_new_subject'=>'Nueva solicitud de desistimiento - Pedido','admin_new_request'=>'Se ha enviado una nueva solicitud de desistimiento.','view_admin'=>'Ver solicitud en administración','manual_products'=>'Producto(s)','manual_products_placeholder'=>'Indique el producto o productos sobre los que desea ejercer el desistimiento.','status_submitted'=>'Enviada','status_in_review'=>'En revisión','status_approved'=>'Aprobada','status_rejected'=>'Rechazada','status_completed'=>'Completada','status_refunded'=>'Reembolsada'],
            'hu'=>[
                'language_name'=>'Hungarian','button_label'=>'Elállás / Szerződés megszüntetése','form_title'=>'Elállás / Szerződés megszüntetése','form_intro'=>'Ezzel az űrlappal online elállási / szerződésmegszüntetési kérelmet nyújthat be a rendelésével kapcsolatban.','lookup_intro'=>'Adja meg a rendelési számot és a számlázási email címet a jogosult tételek megjelenítéséhez.','full_name'=>'Teljes név','email'=>'Email','order_number'=>'Rendelésszám','lookup'=>'Rendelés keresése','products_to_withdraw'=>'Elállással érintett termékek','quantity'=>'Mennyiség','comments'=>'Megjegyzések / további információk','declaration'=>'Kijelentem, hogy elállok a kiválasztott termék(ek)re / rendelésre vonatkozó adásvételi szerződéstől.','review_title'=>'Elállási kérelem ellenőrzése és megerősítése','back'=>'Vissza','submit'=>'Elállási kérelem megerősítése','required_fields'=>'Kérjük, töltse ki az összes kötelező mezőt.','security_failed'=>'A biztonsági ellenőrzés sikertelen. Kérjük, próbálja újra.','order_not_verified'=>'A rendelés nem ellenőrizhető. Kérjük, ellenőrizze a rendelési adatokat.','not_eligible'=>'Ez a rendelés jelenleg nem jogosult online elállásra. Kérjük, vegye fel velünk a kapcsolatot, ha ezt hibásnak gondolja.','no_eligible_items'=>'Ehhez a rendeléshez nem található jogosult tétel.','success_title'=>'Az elállási kérelmet sikeresen elküldte.','success_text'=>'A visszaigazoló emailt elküldtük az email címére.','email_subject'=>'Elállási kérelem beérkezett','received_body'=>'Megkaptuk az elállási / szerződésmegszüntetési kérelmét.','request_id'=>'Kérelem azonosító','proof_hash'=>'Bizonyító hash','reference_code'=>'Azonosító kód','name'=>'Név','order'=>'Rendelés','submitted_at'=>'Beküldés ideje','products'=>'Termék(ek)','declaration_label'=>'Nyilatkozat','next_steps'=>'A visszaküldés és visszatérítés folyamatáról további tájékoztatást fog kapni, az áruház szabályzata és az alkalmazandó jog szerint.','admin_new_subject'=>'Új elállási kérelem - Rendelés','admin_new_request'=>'Új elállási kérelem érkezett.','view_admin'=>'Kérelem megtekintése az adminban','manual_products'=>'Termék(ek)','manual_products_placeholder'=>'Adja meg, mely termék(ek)re vonatkozóan kíván élni az elállási jogával.','status_submitted'=>'Beküldve','status_in_review'=>'Ellenőrzés alatt','status_approved'=>'Jóváhagyva','status_rejected'=>'Elutasítva','status_completed'=>'Befejezve','status_refunded'=>'Visszatérítve'],
        ];
    }

    protected function normalize_lang($lang): string {
        $lang = strtolower((string)$lang);
        if (strpos($lang, '_') !== false) { $lang = substr($lang, 0, 2); }
        return in_array($lang, ['en','el','es','hu'], true) ? $lang : 'en';
    }

    protected function current_lang(): string {
        if ($this->active_lang) { return $this->active_lang; }
        $settings = $this->get_settings();
        if (!empty($settings['language']) && $settings['language'] !== 'auto') { return $this->normalize_lang($settings['language']); }
        if (!empty($_GET['lang'])) { return $this->normalize_lang(sanitize_text_field(wp_unslash($_GET['lang']))); }
        $wpml = apply_filters('wpml_current_language', null);
        if ($wpml) { return $this->normalize_lang($wpml); }
        if (defined('ICL_LANGUAGE_CODE')) { return $this->normalize_lang(ICL_LANGUAGE_CODE); }
        if (function_exists('pll_current_language')) { $pll = pll_current_language('slug'); if ($pll) { return $this->normalize_lang($pll); } }
        return $this->normalize_lang(get_locale());
    }

    protected function t(string $key): string {
        $all = $this->translations(); $lang = $this->current_lang();
        return $all[$lang][$key] ?? $all['en'][$key] ?? $key;
    }
}

